from pathlib import Path

from modules.vlan_manager import load_vlans
from modules.device_manager import load_devices
from modules.firewall_manager import load_firewall_rules
from datetime import datetime


REPORT_FILE = Path("reports/network_report.md")


def get_vlan_name(vlans, vlan_id):
    for vlan in vlans:
        if vlan["vlan_id"] == vlan_id:
            return vlan["name"]

    return "Unknown"


def generate_markdown_report():

    vlans = load_vlans()
    devices = load_devices()
    rules = load_firewall_rules()

    timestamp = datetime.now().strftime(
        "%Y-%m-%d %H:%M:%S"
    )

    with open(REPORT_FILE, "w") as file:

        # Title
        file.write("# SentinelMap Network Report\n\n")

        file.write("Generated by SentinelMap\n\n")
        file.write(f"Generated: {timestamp}\n\n")

        # VLAN Section
        file.write("## VLAN Summary\n\n")

        if not vlans:
            file.write("No VLANs documented.\n\n")
        else:
            for vlan in vlans:
                file.write(f"### VLAN {vlan['vlan_id']} - {vlan['name']}\n")
                file.write(f"- Subnet: {vlan['subnet']}\n")
                file.write(f"- Gateway: {vlan['gateway']}\n")
                file.write(f"- Purpose: {vlan['purpose']}\n")
                file.write(f"- Security Notes: {vlan['security_notes']}\n\n")

        # Device Section
        file.write("## Device Summary\n\n")

        if not devices:
            file.write("No devices documented.\n\n")
        else:
            for device in devices:
                file.write(f"### {device['hostname']}\n")
                file.write(f"- Type: {device['device_type']}\n")
                file.write(f"- IP Address: {device['ip_address']}\n")
                file.write(f"- VLAN ID: {device['vlan_id']}\n")
                file.write(f"- Location: {device['location']}\n")
                file.write(f"- Role: {device['role']}\n")
                file.write(f"- Notes: {device['notes']}\n\n")

        # Firewall Rule Section
        file.write("## Firewall Rules\n\n")

        if not rules:
            file.write("No firewall rules documented.\n\n")
        else:
            for rule in rules:
                file.write(f"### Rule {rule['rule_id']}\n")
                
                source_name = get_vlan_name(vlans, rule["source_vlan"])
                destination_name = get_vlan_name(vlans, rule["destination_vlan"])

                file.write(f"- Source VLAN: {rule['source_vlan']} - {source_name}\n")
                file.write(f"- Destination VLAN: {rule['destination_vlan']} - {destination_name}\n")
                file.write(f"- Protocol: {rule['protocol']}\n")
                file.write(f"- Port: {rule['port']}\n")
                file.write(f"- Action: {rule['action']}\n")
                file.write(f"- Purpose: {rule['purpose']}\n\n")

        # Traffic Summary Section
        file.write("## Traffic Summary\n\n")

        if not vlans:
            file.write("No VLANs documented.\n\n")
        else:
            for vlan in vlans:
                source_vlan = vlan["vlan_id"]
                source_name = vlan["name"]

                file.write(f"### VLAN {source_vlan} - {source_name}\n\n")

                matching_rules = [
                    rule for rule in rules
                    if rule["source_vlan"] == source_vlan
                ]

                if not matching_rules:
                    file.write("No documented outbound firewall rules.\n\n")
                    continue

                for rule in matching_rules:
                    destination_name = get_vlan_name(
                        vlans,
                        rule["destination_vlan"]
                    )

                    file.write(
                        f"- {rule['action'].upper()} -> "
                        f"VLAN {rule['destination_vlan']} "
                        f"({destination_name}) "
                        f"{rule['protocol']}/{rule['port']}\n"
                    )

                    file.write(f"  - Why: {rule['purpose']}\n")

                file.write("\n")

    print(f"Markdown report generated: {REPORT_FILE}")